import Head from 'next/head'
import styles from '../styles/Signin.module.css'

export default function Signin() {
  const onClick = async () => {
    window.connectToHashPack();
  }

  return (
    <div className={styles.body}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.formSignin}>
        <form>
          {/* <img className="mb-4" src="/bootstrap-logo.svg" alt="" width="72" height="57"></img> */}
          <h1 className="mb-1 fw-normal">TwittBar</h1>
          <p className="mb-3">Vault to transfer Hbar(ℏ) via Twitter handle</p>
          {/* <div className="form-floating">
            <input type="email" className="form-control" id="floatingInput" placeholder="name@example.com" />
            <label>Email address</label>
          </div>
          <div className="form-floating">
            <input type="password" className="form-control" id="floatingPassword" placeholder="Password" />
            <label>Password</label>
          </div>
          <div className="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me" /> Remember me
            </label>
          </div> */}
          <div className="w-100 btn btn-lg btn-primary" onClick={onClick}>Connect Wallet</div>
          <img className="mt-5" src="/built-on-hedera.png" alt="" width="120"></img>
          <p className="mb-3 text-muted">choong.pw &copy; 2022</p>
        </form>
      </main>
    </div>
  )
}
